# Database driver
propel.database = mysql
propel.mysql.tableType = InnoDB
propel.database.encoding = utf8mb4

# Project name
propel.project.name = apigtbot
propel.database.url = mysql:host=localhost;dbname=apigtbot
propel.database.user = apigtbot
propel.database.password = change-me

propel.behavior.goatcheese.class = behavior.GoatCheese.GoatCheese
propel.behavior.add_validator.class = behavior.GoatCheese.Model.AddValidators
propel.behavior.add_tablestamp.class = behavior.GoatCheese.vendor.TableStampBehavior

propel.packageObjectModel = true

propel.addIncludes = true
propel.project.dir = /path/to/apigtbot
propel.schema.dir = ${propel.project.dir}/../schema
propel.output.dir = ${propel.project.dir}/.build
propel.builder.pluralizer.class = builder.util.StandardEnglishPluralizer

propel.addValidators = all
propel.defaultTimeStampFormat = Y-m-d H:i:s
propel.defaultTimeFormat = %X
propel.defaultDateFormat = Y-m-d

propel.default.schema.basename = schema
propel.namespace.autoPackage = false
propel.runtime.phpconf.file = db.php