<?php

/**
 * GENERATED by goatcheese Classes/AutocompleteDecisions.php — do not edit.
 *
 * Which FK columns set_autocomplete turned into autocompletes, and why.
 * `rows>=50` / `rows<50` decisions came from a live COUNT at build time and
 * are REPLAYED from this file on later builds, so an unreachable or empty
 * database cannot change the emitted Form/Service shape. Every other reason
 * is derived from the schema and recomputed on each build.
 *
 * Delete this file and rebuild to re-measure row counts.
 */
return [
    'api_log.id_api_rbac' => ['autocomplete' => false, 'reason' => 'schema', 'rows' => null],
    'api_log.id_authy' => ['autocomplete' => true, 'reason' => 'auth_table', 'rows' => null],
    'authy.id_authy_group' => ['autocomplete' => false, 'reason' => 'schema', 'rows' => null],
    'authy_group_x.id_authy_group' => ['autocomplete' => false, 'reason' => 'schema', 'rows' => null],
    'bot_command.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'bot_decision.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'bot_event.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'bot_order.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'fleet_slot.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'grid_run_audit.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'push_device.id_authy' => ['autocomplete' => true, 'reason' => 'auth_table', 'rows' => null],
    'regime_episode.id_fleet_slot' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'regime_episode.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
    'trade_cycle.id_grid_run' => ['autocomplete' => true, 'reason' => 'schema', 'rows' => null],
];
