<?php
// This file generated by Propel 1.7.3-dev convert-conf target
// from XML runtime conf file /path/to/apigtbot/.admin/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'apigtbot' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=apigtbot;charset=utf8;',
        'user' => 'apigtbot',
        'password' => 'change-me',
      ),
    ),
    'default' => 'apigtbot',
  ),
  'generator_version' => '1.7.3-dev',
);
return $conf;