<?php
// Auto-generated by gc build (Parameters/with_mcp.php) — do not edit.
return array (
  'name' => 'apigtbot',
  'about' => 'Paper-trading crypto bot: grid and trend runs, orders, decisions, PnL, refits and bot commands',
  'keywords' => 
  array (
    0 => 'apigtbot',
    1 => 'trading bot',
    2 => 'crypto',
    3 => 'binance',
    4 => 'grid',
    5 => 'trend',
    6 => 'pnl',
    7 => 'refit',
    8 => 'bot run',
    9 => 'order',
  ),
  'missing' => 
  array (
  ),
);
