<?php
// AUTO-GENERATED by gc build (ApiGoat\Mcp\VersionStamp) — do not edit.
// MCP tool-list version + what changed since the previous tool list;
// surfaced by McpServer::initialize (serverInfo.version, instructions).
return array (
  'version' => '2026.09.19-96192c',
  'tools' => 
  array (
    0 => 'crm_create',
    1 => 'crm_delete',
    2 => 'crm_describe',
    3 => 'crm_get',
    4 => 'crm_list',
    5 => 'crm_update',
    6 => 'gc_identity_update',
    7 => 'gtbot_alloc_mode',
    8 => 'gtbot_backtest',
    9 => 'gtbot_budget',
    10 => 'gtbot_create_run',
    11 => 'gtbot_decisions',
    12 => 'gtbot_events',
    13 => 'gtbot_kill',
    14 => 'gtbot_market',
    15 => 'gtbot_pnl_report',
    16 => 'gtbot_preview_grid',
    17 => 'gtbot_purge_run',
    18 => 'gtbot_refit_proposal',
    19 => 'gtbot_retire_run',
    20 => 'gtbot_routine_brief',
    21 => 'gtbot_set_grid',
    22 => 'gtbot_start',
    23 => 'gtbot_status',
    24 => 'gtbot_stop',
  ),
  'changed_at' => '2026-09-19 11:09',
  'added' => 
  array (
    0 => 'gtbot_alloc_mode',
    1 => 'gtbot_budget',
    2 => 'gtbot_purge_run',
    3 => 'gtbot_retire_run',
  ),
  'removed' => 
  array (
  ),
  'previous_version' => '2026.09.09-0c4670',
);
