<?php

namespace App;


$omMap = [
    [
        'name' => 'BotOrder',
        'desc' => 'Orders',
        'parent_table' => 'grid_run',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Grid Run - Order',
    ],
    [
        'name' => 'TradeCycle',
        'desc' => 'Trade Cycles',
        'parent_table' => 'grid_run',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Grid Run - Trade Cycle',
    ],
    [
        'name' => 'BotEvent',
        'desc' => 'Events',
        'parent_table' => 'grid_run',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Grid Run - Event',
    ],
    [
        'name' => 'BotCommand',
        'desc' => 'Commands',
        'parent_table' => 'grid_run',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Grid Run - Command',
    ],
    [
        'name' => 'BotDecision',
        'desc' => 'Refit Decisions',
        'parent_table' => 'grid_run',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Grid Run - Refit Decision',
    ],
    [
        'name' => 'AuthyGroupX',
        'desc' => 'Groups',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Group',
    ],
    [
        'name' => 'TemplateFile',
        'desc' => 'Files',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'File',
    ],
    [
        'name' => 'AuthyRefreshToken',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'AuthyRefreshToken',
    ],
    [
        'name' => 'GridRunAudit',
        'desc' => 'Change histories',
        'parent_table' => 'grid_run',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Grid Run - Change history',
    ],
    [
        'name' => 'OauthClient',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'OauthClient',
    ],
    [
        'name' => 'OauthAuthCode',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'OauthAuthCode',
    ],
    [
        'name' => 'OauthAccessToken',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'OauthAccessToken',
    ],
    [
        'name' => 'OauthRefreshToken',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'OauthRefreshToken',
    ],
    [
        'name' => 'MessageI18n',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'MessageI18n',
    ],
    [
        'name' => 'Authy',
        'desc' => 'Users',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'authy_group_x',
            'authy_log',
        ],
        'display' => 'User',
    ],
    [
        'name' => 'PushDevice',
        'desc' => 'Push devices',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Push device',
    ],
    [
        'name' => 'SimWallet',
        'desc' => 'Paper Wallets',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Paper Wallet',
    ],
    [
        'name' => 'MarketSummary',
        'desc' => 'Market Datas',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Market Data',
    ],
    [
        'name' => 'MarketRegime',
        'desc' => 'Regime Histories',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Regime History',
    ],
    [
        'name' => 'MarketCandle',
        'desc' => 'Candless',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Candles',
    ],
    [
        'name' => 'MarketOutlook',
        'desc' => 'Market Outlooks',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Market Outlook',
    ],
    [
        'name' => 'MarketOutlookState',
        'desc' => 'Outlook States',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Outlook State',
    ],
    [
        'name' => 'WalletNav',
        'desc' => 'Wallet NAVs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Wallet NAV',
    ],
    [
        'name' => 'AuthyGroup',
        'desc' => 'Groups',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Group',
    ],
    [
        'name' => 'AuthyLog',
        'desc' => 'Login logs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Login log',
    ],
    [
        'name' => 'Message',
        'desc' => 'Messages',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Message',
    ],
    [
        'name' => 'Config',
        'desc' => 'Settings',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Setting',
    ],
    [
        'name' => 'ApiRbac',
        'desc' => 'API ACLs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'api_log',
        ],
        'display' => 'API ACL',
    ],
    [
        'name' => 'ApiLog',
        'desc' => 'API logs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'API log',
    ],
    [
        'name' => 'Template',
        'desc' => 'Templates',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'template_file',
        ],
        'display' => 'Template',
    ],
    [
        'name' => 'Country',
        'desc' => 'Countries',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Country',
    ],
    [
        'name' => 'GridRun',
        'desc' => 'Grid Runs',
        'parent_table' => null,
        'parent_menu' => 'Trading',
        'child_table' => [
            'bot_order',
            'trade_cycle',
            'bot_event',
            'bot_command',
            'grid_run_audit',
        ],
        'display' => 'Grid Run',
    ],
    [
        'name' => 'FleetSlot',
        'desc' => 'Fleet slots',
        'parent_table' => null,
        'parent_menu' => 'Trading',
        'child_table' => null,
        'display' => 'Fleet slot',
    ],
    [
        'name' => 'RegimeEpisode',
        'desc' => 'Regime episodes',
        'parent_table' => null,
        'parent_menu' => 'Trading',
        'child_table' => null,
        'display' => 'Regime episode',
    ],
];
