<?php

// Auto-generated by the GoatCheese RbacSpec builder on gc build — do not edit.
// Schema facts for the api_rbac seed generator (gc Utils\RbacSeeds).

return [
    'with_api' => true,
    'models' => [
        'ApiLog' => [
            'upload' => false,
            'mass' => false,
        ],
        'ApiRbac' => [
            'upload' => false,
            'mass' => false,
        ],
        'Authy' => [
            'upload' => false,
            'mass' => false,
        ],
        'AuthyGroup' => [
            'upload' => false,
            'mass' => false,
        ],
        'AuthyGroupX' => [
            'upload' => false,
            'mass' => false,
        ],
        'AuthyLog' => [
            'upload' => false,
            'mass' => false,
        ],
        'BotCommand' => [
            'upload' => false,
            'mass' => false,
        ],
        'BotDecision' => [
            'upload' => false,
            'mass' => false,
        ],
        'BotEvent' => [
            'upload' => false,
            'mass' => false,
        ],
        'BotOrder' => [
            'upload' => false,
            'mass' => false,
        ],
        'Config' => [
            'upload' => false,
            'mass' => false,
        ],
        'Country' => [
            'upload' => false,
            'mass' => false,
        ],
        'GridRun' => [
            'upload' => false,
            'mass' => false,
        ],
        'MarketRegime' => [
            'upload' => false,
            'mass' => false,
        ],
        'MarketSummary' => [
            'upload' => false,
            'mass' => false,
        ],
        'Message' => [
            'upload' => false,
            'mass' => false,
        ],
        'PushDevice' => [
            'upload' => false,
            'mass' => false,
        ],
        'SimWallet' => [
            'upload' => false,
            'mass' => false,
        ],
        'Template' => [
            'upload' => false,
            'mass' => false,
        ],
        'TemplateFile' => [
            'upload' => true,
            'mass' => false,
        ],
        'TradeCycle' => [
            'upload' => false,
            'mass' => false,
        ],
    ],
];
