<?php

namespace App;


return [
    [
        'name' => 'GridRun',
        'desc' => 'Grid Runs',
        'index' => 0,
        'parent_menu' => 'Trading',
        'subtitle' => null,
        'icon' => 'ri-line-chart-line',
        'group_icon' => 'ri-line-chart-line',
        'group_order' => 10,
    ],
    [
        'name' => 'Settings',
        'desc' => 'Settings',
        'index' => 1,
        'parent_menu' => null,
        'route' => '/',
        'icon' => 'ri-settings-3-line',
    ],
    [
        'name' => 'PushDevice',
        'desc' => 'Push devices',
        'index' => 210,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'Authy',
        'desc' => 'Users',
        'index' => 200,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'AuthyGroup',
        'desc' => 'Groups',
        'index' => 50,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'Message',
        'desc' => 'Messages',
        'index' => 10,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'MarketRegime',
        'desc' => 'Regime Histories',
        'index' => 6,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'SimWallet',
        'desc' => 'Paper Wallets',
        'index' => 6,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'MarketSummary',
        'desc' => 'Market Datas',
        'index' => 5,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'ApiLog',
        'desc' => 'API logs',
        'index' => 0,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'ApiRbac',
        'desc' => 'API ACLs',
        'index' => 0,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'AuthyLog',
        'desc' => 'Login logs',
        'index' => 0,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'Config',
        'desc' => 'Settings',
        'index' => 0,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'Country',
        'desc' => 'Countries',
        'index' => 0,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
    [
        'name' => 'Template',
        'desc' => 'Templates',
        'index' => 0,
        'parent_menu' => 'Settings',
        'subtitle' => null,
        'icon' => null,
        'folded' => true,
    ],
];
